"""Campaign YAML schema.

Validated before any GPU is allocated -- and before the input structure is even
opened -- so a bad campaign file fails in seconds rather than forty minutes into
RFD3.

Everything checkable from the YAML alone is checked here, including contig and
selection syntax: `CampaignConfig.model_validate` succeeding means the campaign
is well-formed, not merely well-shaped. Checks that genuinely need coordinates
-- residues existing, selections colliding, gap-aware lengths -- live in
`spec.resolve`.

Per-model differences live in one `MODEL_CAPABILITIES` table rather than in
scattered conditionals. Adding a model is a row; omitting a field is a KeyError
at import rather than a silent fall-through.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from .contig import (
    Component,
    expected_output_chains,
    parse_contig,
    parse_residue_selection,
)

__all__ = [
    "CampaignConfig",
    "CrossValidationConfig",
    "FoldingModel",
    "GeneralConfig",
    "IpsaeConfig",
    "KitCard",
    "MODEL_CAPABILITIES",
    "Mode",
    "ModelCapabilities",
    "MpnnConfig",
    "MpnnType",
    "MsaConfig",
    "RefoldingConfig",
    "Rfd3Config",
    "RunConfig",
    "SeedStyle",
    "SpecConfig",
    "Weights",
    "folding_variant",
    "seed_sequence",
]


class Mode(StrEnum):
    """Anthropic kit acceleration mode. A mode that cannot engage exits 3."""

    OFF = "off"
    EXACT = "exact"
    FAST = "fast"
    BIG = "big"


class KitCard(StrEnum):
    """`--config` card. The kits ship these three only."""

    H100 = "h100"
    H200 = "h200"
    A100 = "a100"


class FoldingModel(StrEnum):
    ESMFOLD2 = "esmfold2"
    ESMFOLD2_FAST = "esmfold2-fast"
    BOLTZ2 = "boltz2"
    AF3_JAX = "af3_jax"


class Weights(StrEnum):
    """Which checkpoint af3_jax loads. The kit ships OpenFold3 by default."""

    OPENFOLD3 = "openfold3"
    AF3_NATIVE = "af3_native"


class MpnnType(StrEnum):
    SOLUBLE = "soluble"
    PROTEIN = "protein"
    LIGAND = "ligand"


class SeedStyle(StrEnum):
    """How a model is asked for several seeds.

    LIST -- `--seeds a,b,c`, seeds chosen by us and reproducible.
    COUNT -- `--num_seeds N`, seeds generated by the model from the one in its
    input; the concrete values are readable only from its output.
    """

    LIST = "list"
    COUNT = "count"


@dataclass(frozen=True)
class ModelCapabilities:
    """What one folding model supports. One row per model, no conditionals."""

    supports_templates: bool
    consumes_msa: bool
    seed_style: SeedStyle
    # Keyed by whether the step supplies an MSA. None when the model's variant
    # is not derived per step.
    derived_variants: dict[bool, str] | None = None
    fixed_variant: str | None = None
    default_weights: Weights | None = None

    @property
    def accepts_weights(self) -> bool:
        return self.default_weights is not None

    def variant_for(self, msa_present: bool) -> str | None:
        if self.derived_variants is not None:
            return self.derived_variants[msa_present]
        return self.fixed_variant


MODEL_CAPABILITIES: dict[FoldingModel, ModelCapabilities] = {
    # `--variant` conflates model choice with MSA presence, so the campaign
    # names the model and the step supplies the MSA (esmfold2/README.md:72-73).
    FoldingModel.ESMFOLD2: ModelCapabilities(
        supports_templates=False,
        consumes_msa=True,
        seed_style=SeedStyle.LIST,
        derived_variants={False: "full_nomsa", True: "full_msa"},
    ),
    FoldingModel.ESMFOLD2_FAST: ModelCapabilities(
        supports_templates=False,
        consumes_msa=False,
        seed_style=SeedStyle.LIST,
        derived_variants={False: "fast", True: "fast"},
    ),
    FoldingModel.BOLTZ2: ModelCapabilities(
        # Templates unverified against the kit; left False so a campaign cannot
        # silently request something that may be ignored.
        supports_templates=False,
        consumes_msa=True,
        seed_style=SeedStyle.LIST,
    ),
    FoldingModel.AF3_JAX: ModelCapabilities(
        supports_templates=True,
        consumes_msa=True,
        seed_style=SeedStyle.COUNT,
        fixed_variant="p2",
        default_weights=Weights.OPENFOLD3,
    ),
}

# Modal GPU string -> kit card. GPUs absent from this table have no kit config,
# so a folding step cannot run on them: the mode would print NOT ACTIVE and
# exit 3 rather than falling back.
GPU_TO_CARD: dict[str, KitCard] = {
    "A100": KitCard.A100,
    "A100-40GB": KitCard.A100,
    "A100-80GB": KitCard.A100,
    "H100": KitCard.H100,
    "H200": KitCard.H200,
}

# `--n_gpu P` shards ONE prediction across P GPUs of a single host, and the kits
# accept only these values. It is not concurrency; that is `max_concurrent`.
VALID_GPU_SHARDS = (1, 2, 4, 8)


def folding_variant(model: FoldingModel, msa_present: bool) -> str | None:
    """The kit's `--variant` for a step, derived rather than configured."""
    return MODEL_CAPABILITIES[model].variant_for(msa_present)


def seed_sequence(base_seed: int, count: int) -> list[int]:
    """Concrete seeds for a step, so a re-run is comparable to its original."""
    if count < 1:
        raise ValueError(f"need at least one seed, got {count}")
    return [base_seed + offset for offset in range(count)]


def _split_commas(value: str) -> list[str]:
    """One definition of the comma-separated shorthand several fields accept."""
    return [part.strip() for part in value.split(",") if part.strip()]


class _Base(BaseModel):
    """Reject unknown keys: a typo should fail, not be silently ignored."""

    model_config = ConfigDict(extra="forbid", use_enum_values=False)


class GeneralConfig(_Base):
    chain_binder: str = "A"
    chain_targets: list[str]
    name_design_campaign: str
    run_name: str
    base_seed: int = 0
    seq_targets: dict[str, str] = Field(default_factory=dict)

    @field_validator("chain_targets", mode="before")
    @classmethod
    def _accept_comma_string(cls, value: Any) -> Any:
        return _split_commas(value) if isinstance(value, str) else value

    @model_validator(mode="before")
    @classmethod
    def _accept_comma_sequences(cls, data: Any) -> Any:
        """`seq_targets` as one comma-joined string, paired with chain_targets."""
        if not isinstance(data, dict) or not isinstance(data.get("seq_targets"), str):
            return data

        chains = data.get("chain_targets")
        if isinstance(chains, str):
            chains = _split_commas(chains)
        parts = _split_commas(data["seq_targets"])
        if not chains or len(chains) != len(parts):
            raise ValueError(
                f"seq_targets has {len(parts)} comma-separated sequence(s) but "
                f"chain_targets names {len(chains or [])} chain(s); use a mapping "
                "of chain id to sequence instead"
            )
        return {**data, "seq_targets": dict(zip(chains, parts))}

    @model_validator(mode="after")
    def _check_chains(self) -> GeneralConfig:
        if not self.chain_targets:
            raise ValueError("chain_targets must name at least one chain")
        if len(set(self.chain_targets)) != len(self.chain_targets):
            raise ValueError(f"duplicate target chains: {self.chain_targets}")
        if self.chain_binder in self.chain_targets:
            raise ValueError(
                f"chain_binder {self.chain_binder!r} also appears in chain_targets"
            )
        return self

    @property
    def all_chains(self) -> list[str]:
        """Expected output chains: binder first, then targets in contig order."""
        return [self.chain_binder, *self.chain_targets]


class SpecConfig(_Base):
    """One RFD3 design specification.

    An explicit `name` rather than a list index, so output keys stay stable when
    specs are added, removed or reordered -- otherwise a resumed run matches
    `skip_existing` against the previous run's outputs under shifted names.
    """

    name: str
    contig: str
    unindex: str | None = None
    select_fixed_atoms: dict[str, str] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _check_selections(self) -> SpecConfig:
        # Parsed here so a malformed contig fails config validation rather than
        # surviving until the input structure is loaded.
        self.components  # noqa: B018 - raises on a bad contig

        unindexed = set(parse_residue_selection(self.unindex or ""))
        if self.select_fixed_atoms and not unindexed:
            raise ValueError(
                f"spec {self.name!r} sets select_fixed_atoms without unindex; "
                "there is nothing for it to apply to"
            )
        for selector in self.select_fixed_atoms:
            outside = sorted(set(parse_residue_selection(selector)) - unindexed)
            if outside:
                from .contig import format_residues

                raise ValueError(
                    f"spec {self.name!r}: select_fixed_atoms key {selector!r} "
                    f"covers residue(s) that are not unindexed, e.g. "
                    f"{format_residues(outside)}"
                )
        return self

    @property
    def components(self) -> tuple[Component, ...]:
        return parse_contig(self.contig)

    @property
    def unindexed_residues(self) -> tuple[tuple[str, int], ...]:
        return parse_residue_selection(self.unindex or "")


class Rfd3Config(_Base):
    gpu: str = "A100-80GB"
    max_concurrent: int = Field(default=1, ge=1)
    path_input_structure: str
    specs: list[SpecConfig]

    hotspots: str = ""
    infer_ori_strategy: Literal["com", "hotspots"] = "hotspots"
    is_non_loopy: bool | None = None
    dialect: int = 2
    ligand: str | None = None

    # Always derived from the contig; see spec.resolve. Present only so a YAML
    # carrying one is rejected loudly rather than silently believed.
    length: str | None = None

    n_batches: int = Field(default=1, ge=1)
    diffusion_batch_size: int = Field(default=8, ge=1)

    num_timesteps: int = Field(default=200, ge=1)
    step_scale: float = 1.5
    gamma_0: float = 0.6

    threshold_interresidue_clashes_backbone: int = 0
    threshold_interresidue_clashes_sidechain: int = 3
    threshold_loop_fraction: float = 0.5
    threshold_radius_gyration_multiplier: float = 1.1
    threshold_hotspot_contacts: float = 0.4

    @field_validator("path_input_structure")
    @classmethod
    def _normalise_path(cls, value: str) -> str:
        """Backslashes do not resolve in Modal's Linux containers."""
        return value.replace("\\", "/")

    @field_validator("ligand")
    @classmethod
    def _ligand_ranges_are_not_supported(cls, value: str | None) -> str | None:
        """RFD3 splits ligand strings on ',' or '-', so a hyphen reads as a range."""
        if value and "-" in value:
            raise ValueError(
                f"ligand {value!r} contains '-', which RFD3 parses as a range "
                "pattern; list instances separately, e.g. 'E703,E704'"
            )
        return value

    @model_validator(mode="after")
    def _check_specs(self) -> Rfd3Config:
        if not self.specs:
            raise ValueError("at least one spec is required")
        names = [spec.name for spec in self.specs]
        if len(set(names)) != len(names):
            raise ValueError(f"spec names must be unique, got {names}")
        if self.length is not None:
            raise ValueError(
                f"length is derived from the contig, not configured (got "
                f"{self.length!r}). Remove it, or set it to null."
            )
        if self.infer_ori_strategy == "hotspots" and not self.hotspots:
            raise ValueError(
                "infer_ori_strategy is 'hotspots' but no hotspots are given"
            )
        parse_residue_selection(self.hotspots)  # raises on malformed hotspots
        return self

    @property
    def designs_per_spec(self) -> int:
        return self.n_batches * self.diffusion_batch_size

    @property
    def total_designs(self) -> int:
        return self.designs_per_spec * len(self.specs)


class MpnnConfig(_Base):
    gpu: str = "L40S"
    max_concurrent: int = Field(default=1, ge=1)
    mpnn_type: MpnnType = MpnnType.SOLUBLE
    mpnn_sampling_temp: float = Field(default=0.1, gt=0)
    num_seqs: int = Field(default=8, ge=1)
    rm_aa: str = "C"


class _FoldingBase(_Base):
    model: FoldingModel
    mode: Mode = Mode.FAST
    gpu: str = "A100-80GB"
    n_gpu_shard: int = 1
    max_concurrent: int = Field(default=1, ge=1)
    chunk_size: int = Field(default=16, ge=1)
    target_template: bool = False
    variant: str | None = None
    weights: Weights | None = None

    @field_validator("gpu")
    @classmethod
    def _gpu_has_a_kit_card(cls, value: str) -> str:
        if value not in GPU_TO_CARD:
            raise ValueError(
                f"gpu {value!r} has no kit card; folding steps need one of "
                f"{sorted(GPU_TO_CARD)}. A mode that cannot engage exits 3."
            )
        return value

    @model_validator(mode="after")
    def _check_folding(self) -> _FoldingBase:
        capabilities = MODEL_CAPABILITIES[self.model]

        if self.n_gpu_shard not in VALID_GPU_SHARDS:
            raise ValueError(
                f"n_gpu_shard must be one of {VALID_GPU_SHARDS}, got {self.n_gpu_shard}"
            )
        if self.n_gpu_shard > 1 and self.mode is not Mode.BIG:
            raise ValueError(
                f"n_gpu_shard={self.n_gpu_shard} requires mode 'big'; it shards one "
                f"prediction across GPUs, and mode is {self.mode.value!r}. For "
                "concurrency use max_concurrent."
            )

        if self.target_template and not capabilities.supports_templates:
            raise ValueError(
                f"{self.model.value} does not support templates; "
                "set target_template: false"
            )

        if capabilities.derived_variants is not None:
            if self.variant is not None:
                raise ValueError(
                    f"variant is derived per step for {self.model.value}, not set "
                    "in config: apo has no MSA, holo has one"
                )
        elif capabilities.fixed_variant is not None:
            if self.variant is None:
                self.variant = capabilities.fixed_variant
        elif self.variant is not None:
            raise ValueError(f"{self.model.value} takes no variant")

        if self.weights is not None and not capabilities.accepts_weights:
            raise ValueError(
                f"weights is meaningful only for models that ship several "
                f"checkpoints, not {self.model.value}"
            )
        if self.weights is None:
            self.weights = capabilities.default_weights

        return self

    @property
    def kit_config(self) -> KitCard:
        """The `--config` card, derived from the GPU rather than restated."""
        return GPU_TO_CARD[self.gpu]

    @property
    def capabilities(self) -> ModelCapabilities:
        return MODEL_CAPABILITIES[self.model]

    @property
    def consumes_msa(self) -> bool:
        """Whether this model reads a target MSA at all.

        False for esmfold2-fast, which means a cached target MSA is built and
        then ignored -- a legitimate cheap-screening choice, but one worth
        logging rather than discovering from a flat ipTM distribution.
        """
        return self.capabilities.consumes_msa

    @property
    def seed_style(self) -> SeedStyle:
        return self.capabilities.seed_style


class RefoldingConfig(_FoldingBase):
    threshold_plddt_binder: float = 70.0
    threshold_rmsd_apo_holo: float = 4.0
    threshold_rmsd_motif: float = 2.0
    threshold_ipTM: float = 0.3


class CrossValidationConfig(_FoldingBase):
    num_seeds: int = Field(default=5, ge=1)


class MsaConfig(_Base):
    host_url: str = "https://api.colabfold.com"
    use_env: bool = True
    use_filter: bool = True
    pairing_strategy: Literal["greedy", "complete"] = "greedy"
    username: str | None = None
    password: str | None = None
    auth_header: str | None = None

    @model_validator(mode="after")
    def _one_auth_method(self) -> MsaConfig:
        basic = self.username is not None or self.password is not None
        if basic and self.auth_header is not None:
            raise ValueError("use either username/password or auth_header, not both")
        if (self.username is None) != (self.password is None):
            raise ValueError("username and password must be given together")
        return self

    @property
    def needs_secret(self) -> bool:
        """Credentials are the one thing requiring a Modal secret."""
        return self.username is not None or self.auth_header is not None


class IpsaeConfig(_Base):
    # Explicit because every existing implementation defaults to 15.
    pae_cutoff: float = 10.0
    dist_cutoff: float = 10.0


class RunConfig(_Base):
    dry_run: bool = False


class CampaignConfig(_Base):
    general: GeneralConfig
    rfdiffusion3: Rfd3Config
    mpnn: MpnnConfig
    refolding: RefoldingConfig
    cross_validation: CrossValidationConfig
    msa: MsaConfig = Field(default_factory=MsaConfig)
    ipsae: IpsaeConfig = Field(default_factory=IpsaeConfig)
    run: RunConfig = Field(default_factory=RunConfig)

    @model_validator(mode="before")
    @classmethod
    def _accept_hyphenated_key(cls, data: Any) -> Any:
        """The original YAML used `cross-validation`, awkward to reach in Python."""
        if isinstance(data, dict) and "cross-validation" in data:
            if "cross_validation" in data:
                raise ValueError(
                    "both 'cross-validation' and 'cross_validation' are present; "
                    "keep only 'cross_validation'"
                )
            data = dict(data)
            data["cross_validation"] = data.pop("cross-validation")
        return data

    @model_validator(mode="after")
    def _check_campaign(self) -> CampaignConfig:
        declared = set(self.general.chain_targets)
        described = set(self.general.seq_targets)
        if described and described != declared:
            raise ValueError(
                f"seq_targets describes chains {sorted(described)} but "
                f"chain_targets names {sorted(declared)}"
            )

        # Text-only, so it belongs here rather than waiting for the structure.
        expected = self.general.all_chains
        for spec in self.rfdiffusion3.specs:
            chains = expected_output_chains(spec.components)
            if chains != expected:
                raise ValueError(
                    f"spec {spec.name!r}: the contig produces output chains "
                    f"{chains}, but the campaign declares {expected}. Output "
                    "chains are lettered from A in contig order, so the binder "
                    "segment comes first and one segment must follow per "
                    "declared target chain."
                )
        return self

    @property
    def cross_validation_seeds(self) -> list[int]:
        return seed_sequence(self.general.base_seed, self.cross_validation.num_seeds)
